# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 471b4482abbc2258b75c731528f3faf591ed378f9f11810483e397f1821dd51842eebe1207e0d3cb3d6eb8594dc898bbe89841bd4e281e4c2542db5976fb3675

test:
  secret_key_base: 88cf09dc341d1eb997a929c501721b36dacc4193b07b2acf999f1461bf8a654f883ab57b64dd753d0c2918c237b90860aeb2be1100a010903de56157a8a25811

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
